feat: 스웨거 도입
miind-palace/mind-palace-BACKEND pull request #30
Opened 2023-10-15 12:42 UTC by RE-Heat

2023-10-15 12:42 UTC, RE-Heat commented
나중에 프로덕션 서버도 되는지 확인하려고 설정 추가해놨는데, 배포 후 확인이 필요할 것 같아요

2023-10-16 07:40 UTC, Owonie requested changes
스웨거 도입한 부분은 잘 봤습니다. 변수명 변경 관련해서 한번 만 확인해주시면 될 것 같아요 수고하셨습니다 :)

2023-10-16 07:40 UTC, Owonie commented on src/main/java/com/mindpalace/MP_Backend/config/Workaround.java
> +        openApi.setServers(Arrays.asList(localServer, testServer));
스웨거 설정에서 localServer와 실제 server를 따로 구분할 수 있군요. testServer보단 실제 product 서버라는 뜻이 담긴 변수명으로 선언하는 건 어떨까요?

2023-10-16 10:38 UTC, RE-Heat commented on src/main/java/com/mindpalace/MP_Backend/config/Workaround.java
> +        openApi.setServers(Arrays.asList(localServer, testServer));
testServer -> productionServer로 수정할게요~

2023-10-16 10:44 UTC, closed without merging